
CREATE TABLE  IF NOT EXISTS public.users (
    id serial PRIMARY KEY,
    username VARCHAR(128) NOT NULL UNIQUE,
    passhash VARCHAR(60) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);